server:
  port: 8761
eureka:
  instance:
    hostname: 39.106.77.194
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: https://${eureka.instance.hostname}:${server.port}/eureka/
