#微服务相关配置
eureka:
  client:
    serviceUrl:
      defaultZone: http://39.106.77.194:8761/eureka/
server:
  port: 8765
spring:
  application:
    name: ENTRANCE1


#修改调用超时时间2s
feign:
  client:
    config:
      default:
        connectTimeout: 2000
        readTimeout: 2000